'use strict';
window.FinanceStudio=(()=>{
  const e=Domain.escape,i=Views.icon,b=Views.button;
  const iconIds={Ventas:'sales',Clientes:'clients',Reembolso:'refund',Inversión:'investment',Gasolina:'fuel',Comida:'food',Gimnasio:'gym',Escuela:'school',Personal:'personal',Otro:'other'};
  function pixel(category){return `<svg class="pixel-icon" viewBox="0 0 24 24" aria-hidden="true"><use href="category-icons.svg#${Object.hasOwn(iconIds,category)?iconIds[category]:'other'}"></use></svg>`;}
  function breakdown(){const groups=new Map();Views.periodTransactions().filter(t=>t.type==='expense').forEach(t=>groups.set(t.category,(groups.get(t.category)||0)+t.amount));return [...groups].sort((a,b)=>b[1]-a[1]);}
  function rows(list){const total=breakdown().reduce((n,[,v])=>n+v,0);return list.map(([c,amount])=>`<div class="finance-breakdown-row">${pixel(c)}<div><h3><span>${e(c)}</span><strong>${Domain.money(amount)}</strong></h3>${Views.progress(total?amount/total*100:0)}</div></div>`).join('');}
  function analytics(){const list=breakdown();return `<div class="finance-analytics"><section class="panel"><header class="panel-header"><div class="panel-title"><h2>Entradas y salidas</h2></div><span class="micro-label">6 MESES</span></header><div class="panel-content"><div class="chart-legend"><span><i class="legend-dot"></i>Ingresos</span><span><i class="legend-dot expense"></i>Gastos</span></div>${Views.chart()}</div></section><section class="panel"><header class="panel-header"><div class="panel-title"><h2>El desglose</h2></div>${b(i('arrow-up-right'),'finance-breakdown','small','aria-label="Ver desglose completo"')}</header><div class="panel-content">${list.length?rows(list.slice(0,4)):`<div class="finance-breakdown-empty">${pixel('Ventas')}<p>Registra un gasto para ver cómo se distribuye por categoría.</p>${b('Registrar gasto','add-transaction','small')}</div>`}<p class="tutor-small" style="margin-top:12px">Gastos del periodo · ${list.length} categorías</p></div></section></div>`;}
  function render(){return `<div class="finance-studio">${Views.finance()}</div>`;}
  function picker(selected){const categories=Store.get().categories||DALI_CONFIG.categories;const list=categories.includes(selected)?categories:[selected,...categories];return `<div class="category-picker" role="group" aria-label="Categorías">${list.map(c=>`<button type="button" class="category-chip ${c===selected?'active':''}" data-category-value="${e(c)}" aria-pressed="${c===selected}">${pixel(c)}<span>${e(c)}</span></button>`).join('')}</div>`;}
  function attach(){const select=document.querySelector('#record-form select[name="category"]');if(!select||select.dataset.enhanced||!document.querySelector('#record-form [name="amount"]'))return;select.dataset.enhanced='true';const grid=document.createElement('div');grid.className='form-field full';grid.innerHTML=picker(select.value);select.closest('.form-field').after(grid);grid.addEventListener('click',ev=>{const button=ev.target.closest('[data-category-value]');if(!button)return;select.value=button.dataset.categoryValue;for(const item of grid.querySelectorAll('button')){item.classList.toggle('active',item===button);item.setAttribute('aria-pressed',item===button);}select.dispatchEvent(new Event('change',{bubbles:true}));});select.addEventListener('change',()=>{grid.querySelectorAll('button').forEach(btn=>{btn.classList.toggle('active',btn.dataset.categoryValue===select.value);btn.setAttribute('aria-pressed',btn.dataset.categoryValue===select.value);});});}
  function action(el){if(el.dataset.action==='finance-breakdown'){const list=breakdown();App.openDialog('Gastos por categoría',`<p class="dialog-subtitle">El desglose usa todos los gastos del periodo seleccionado, no los filtros adicionales del historial.</p>${list.length?rows(list):'<p class="tutor-small">No hay gastos en este periodo.</p>'}`);return;}if(el.dataset.action==='finance-detail'){const t=Store.list('transactions').find(x=>x.id===el.dataset.id);if(!t)throw new Error('Movimiento no encontrado.');App.openDialog('Detalles del movimiento',`<div class="category-preview">${pixel(t.category)}<span>${e(t.category)}</span><span class="tag ${t.type==='income'?'green':'red'}">${t.type==='income'?'Ingreso':'Gasto'}</span></div><div class="metric-value" style="margin:17px 0">${Domain.money(t.amount)}</div><h3>${e(t.title)}</h3><p class="tutor-small" style="margin:12px 0">${Views.date(t.date,{day:'numeric',month:'long',year:'numeric'})}</p><p class="body-copy">${e(t.note||'Sin nota.')}</p>${t.origin?'<p class="notice" style="margin-top:16px">Movimiento vinculado a un abono. Revierte el abono desde su origen para mantener los saldos.</p>':''}<div class="form-footer">${b('Cerrar','close-dialog')}${!t.origin?b('Editar','edit','primary',`data-collection="transactions" data-id="${e(t.id)}"`):''}</div>`);}}
  return {pixel,analytics,render,attach,action};
})();
