'use strict';
window.Forms = (()=>{
 const e=Domain.escape, i=Views.icon, b=Views.button;
 const options=(values,selected)=>values.map(v=>{const [value,label]=Array.isArray(v)?v:[v,v];return `<option value="${e(value)}" ${String(value)===String(selected)?'selected':''}>${e(label)}</option>`;}).join('');
 function field(name,label,value='',type='text',extra='',full=false){return `<div class="form-field ${full?'full':''}"><label for="field-${name}">${label}</label><input id="field-${name}" class="input" name="${name}" type="${type}" value="${e(value)}" ${extra} ${['number'].includes(type)?'inputmode="decimal"':''} ${type==='text'?'maxlength="200"':''}></div>`;}
 function select(name,label,values,value='',full=false){return `<div class="form-field ${full?'full':''}"><label for="field-${name}">${label}</label><select id="field-${name}" class="select" name="${name}">${options(values,value)}</select></div>`;}
 function area(name,label,value='',extra=''){return `<div class="form-field full"><label for="field-${name}">${label}</label><textarea id="field-${name}" name="${name}" maxlength="15000" ${extra}>${e(value)}</textarea></div>`;}
 const check=(name,label,value=false)=>`<label class="form-check"><input type="checkbox" name="${name}" ${value?'checked':''}>${label}</label>`;
 function form(title,subtitle,fields,onSubmit,submit='Guardar'){App.openDialog(title,`<p class="dialog-subtitle">${e(subtitle)}</p><form id="record-form"><div class="form-grid">${fields}</div><p id="form-error" class="form-error" role="alert"></p><div class="form-footer">${b('Cancelar','close-dialog') }<button type="submit" class="button primary">${i('check')}${submit}</button></div></form>`);document.getElementById('record-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const submitButton=form.querySelector('[type="submit"]');submitButton.disabled=true;try{const data=Object.fromEntries(new FormData(form));onSubmit(data);if(document.getElementById('record-form')===form){App.closeDialog();App.render();App.toast('Guardado.');}}catch(err){const error=document.getElementById('form-error');if(error)error.textContent=err.message;submitButton.disabled=false;}});}
 function edit(collection,id,preset={}){const old=id?Store.list(collection).find(x=>x.id===id):{};if(!old)throw new Error('No se encontró el registro.');if(collection==='routines'&&old.tutorKey){App.toast('Esta rutina pertenece a un plan versionado. Edita el JSON e importa una nueva revisión desde Tutor.','error');return;}const r={...old,...preset},isEdit=!!id,today=Domain.today(),dateField=field('date','Fecha',r.date||today,'date','required',false);let fields='',title='Nuevo registro';const baseCategories=Store.get().categories||DALI_CONFIG.categories;const categories=r.category&&!baseCategories.includes(r.category)?[r.category,...baseCategories]:baseCategories;
 if(collection==='transactions'){if(r.origin){App.toast('Este movimiento proviene de un abono. Reviértelo desde su registro de origen para mantener los saldos consistentes.','error');return;}if(!id&&!preset.amount){amountStep(r);return;}title=isEdit?'Editar movimiento':'Detalles del movimiento';fields=select('type','Tipo',[['expense','Gasto'],['income','Ingreso']],r.type||'expense')+field('amount','Monto · MXN',(r.amount||0)/100,'text','inputmode="decimal" required pattern="[0-9]+(\\.[0-9]{1,2})?"')+field('title','Concepto',r.title,'text','required',true)+select('category','Categoría',categories,r.category||'Personal')+dateField+area('note','Nota opcional',r.note);}
 if(collection==='bills'||collection==='loans'){title=(isEdit?'Editar ':'Nuevo ')+(collection==='bills'?'pago pendiente':'préstamo');fields=field('title',collection==='bills'?'Concepto':'Persona / concepto',r.title,'text','required',true)+field('amount','Monto total · MXN',r.amount?r.amount/100:'','text','inputmode="decimal" required')+field('date',collection==='bills'?'Vencimiento':'Siguiente abono',r.date||today,'date','required')+select('category','Categoría',categories,r.category||'Personal')+select('priority','Prioridad',['Normal','Alta','Baja'],r.priority||'Normal')+area('note',collection==='loans'?'Acuerdo de pagos y notas':'Notas / recurrencia acordada',r.note);}
 if(collection==='goals'){title=isEdit?'Editar objetivo':'Dale intención a tu día';fields=field('title','¿Qué quieres lograr?',r.title,'text','required',true)+select('horizon','Horizonte',['diario','semanal','mensual','anual'],r.horizon||'diario')+select('category','Categoría',['Personal','SOMA','Alvento','Rancho','Gimnasio','Escuela','Finanzas','Aprendizaje'],r.category||'Personal')+field('target','Meta (1 = objetivo de casilla)',r.target||1,'number','min="1" max="1000000" step="1" required')+field('progress','Progreso actual',r.progress||0,'number','min="0" max="1000000" step="1" required')+field('unit','Unidad (opcional)',r.unit||'')+field('date','Fecha límite',r.date||today,'date','required')+select('priority','Prioridad',['Normal','Alta','Baja'],r.priority||'Normal')+check('recurring','Repetir al empezar cada periodo, conservando el historial',r.recurring)+check('archived','Archivar este objetivo',r.archived)+area('description','Descripción',r.description)+(r.history?.length?`<div class="form-field full"><label>Historial conservado</label>${r.history.map(h=>`<p class="muted">${e(h.periodKey)} · ${h.progress} / ${h.target}${h.recorded===false?' · Sin actividad registrada':''}</p>`).join('')}</div>`:'');}
 if(collection==='clients'){title=isEdit?'Editar cliente':'Una nueva relación';fields=field('title','Negocio / cliente',r.title,'text','required',true)+field('contact','Nombre de contacto',r.contact)+select('stage','Etapa',DALI_CONFIG.stages,r.stage||'Prospecto')+field('phone','WhatsApp con código de país',r.phone,'tel','placeholder="+52 341 123 4567"')+field('email','Correo',r.email,'email')+field('project','Proyecto / paquete',r.project,'text','',true)+field('amount','Precio total · MXN',r.amount?r.amount/100:0,'text','inputmode="decimal" required')+field('date','Entrega estimada',r.date||today,'date','required')+select('owner','Responsable interno',['Alejandro','Daniel'],r.owner||'Alejandro')+field('nextDate','Fecha de seguimiento',r.nextDate||'','date')+field('nextAction','Siguiente acción',r.nextAction,'text','',true)+area('deliverablesText','Entregables (uno por línea)',(r.deliverables||[]).map(d=>d.title).join('\n'))+area('note','Notas y acuerdo de pagos',r.note);}
 if(collection==='routines'){title=isEdit?'Editar rutina':'Crear rutina';fields=field('title','Nombre de la rutina',r.title,'text','required',true)+select('day','Día de la semana',[[1,'Lunes'],[2,'Martes'],[3,'Miércoles'],[4,'Jueves'],[5,'Viernes'],[6,'Sábado'],[0,'Domingo']],r.day??1,true)+area('exercises','Ejercicios (uno por línea)',r.exercises,'required');}
 if(collection==='metrics'){title=isEdit?'Editar medición':'Un nuevo punto de partida';fields=field('weight','Peso · kg',r.weight||'','number','min="1" max="500" step="0.1" required')+dateField+area('note','Notas / medidas opcionales',r.note);}
 if(collection==='skills'){title=isEdit?'Editar habilidad':'¿Qué quieres aprender?';fields=field('title','Habilidad',r.title,'text','required',true)+field('category','Categoría',r.category||'Aprendizaje')+select('status','Estado',['Activa','Pausada','Completada'],r.status||'Activa')+field('minutes','Minutos disponibles por semana',r.minutes||120,'number','min="1" max="10080" required')+field('date','Fecha objetivo',r.date||today,'date','required')+area('reason','¿Para qué quieres aprenderla?',r.reason);}
 if(collection==='journal'){journal(r,id);return;}
 form(title,'Los cambios se guardan únicamente en este navegador.',fields,data=>{let payload={...data};for(const k of ['title','category','note','description','project'])if(payload[k])payload[k]=payload[k].trim();if('title'in payload&&!payload.title)throw new Error('Escribe un título o concepto.');if(['transactions','bills','loans','clients'].includes(collection)){payload.amount=Domain.cents(data.amount);if(collection!=='clients'&&payload.amount<=0)throw new Error('El monto debe ser mayor a cero.');if((r.payments||[]).reduce((s,p)=>s+p.amount,0)>payload.amount)throw new Error('El total no puede ser menor a los abonos ya registrados.');if(!isEdit&&collection!=='transactions')payload.payments=[];}
 if(collection==='goals'){payload.target=Number(data.target);payload.progress=Number(data.progress);if(payload.progress>payload.target)throw new Error('El progreso no puede superar la meta.');payload.recurring=!!data.recurring;payload.archived=!!data.archived;payload.periodKey=Domain.periodKey(payload.horizon);payload.history=r.history||[];if(isEdit&&r.periodKey!==payload.periodKey)payload.history=[...payload.history,{periodKey:r.periodKey,progress:r.progress,target:r.target}];}
 if(collection==='clients'){const phone=(data.phone||'').replace(/\D/g,'');if(phone&&!/^\d{10,15}$/.test(phone))throw new Error('Usa un teléfono de 10 a 15 dígitos, incluyendo código de país.');payload.phone=phone;payload.deliverables=data.deliverablesText.split('\n').map(x=>x.trim()).filter(Boolean).map(title=>(r.deliverables||[]).find(d=>d.title===title)||{id:Store.uuid(),title,done:false});delete payload.deliverablesText;}
 if(collection==='routines'){payload.day=Number(data.day);payload.exercises=data.exercises.split('\n').map(s=>s.trim()).filter(Boolean).slice(0,30).join('\n');if(!payload.exercises)throw new Error('Agrega al menos un ejercicio.');}
 if(collection==='metrics')payload.weight=Number(data.weight);
 if(collection==='skills'){payload.minutes=Number(data.minutes);payload.tasks=r.tasks||[];if(payload.status==='Completada'&&Domain.learningProgress({...r,...payload})<100)throw new Error('Completa la ruta y la prueba final con evidencia antes de finalizar la habilidad.');}
 Store.put(collection,payload,id);});}
 function amountStep(r={}){App.openDialog('Nuevo movimiento',`<p class="dialog-subtitle">01 / El monto · Después agregaremos los detalles.</p><div class="type-switch"><button data-action="amount-type" data-type="expense" class="${r.type!=='income'?'active':''}">Gasto</button><button data-action="amount-type" data-type="income" class="${r.type==='income'?'active':''}">Ingreso</button></div><label class="sr-only" for="money-pad-input">Monto en pesos mexicanos</label><input id="money-pad-input" class="amount-input" inputmode="decimal" maxlength="13" placeholder="0.00" aria-describedby="amount-help" value=""><p class="amount-caption" id="amount-help">Pesos mexicanos · MXN</p><div class="number-pad">${['1','2','3','4','5','6','7','8','9','.','0','⌫'].map(n=>`<button data-action="pad" data-key="${n}" aria-label="${n==='⌫'?'Borrar último dígito':n}">${n}</button>`).join('')}</div><p id="amount-error" class="form-error" role="alert"></p><div class="form-footer">${b('Cancelar','close-dialog')}${b('Continuar '+i('arrow-right'),'amount-next','primary')}</div>`);UI.moneyType=r.type||'expense';}
 function payment(collection,id){const item=Store.list(collection).find(x=>x.id===id),paymentId=Store.uuid();form(collection==='clients'?'Registrar cobro':'Registrar abono',`${item.title} · Pendiente: ${Domain.money(Domain.outstanding(item))}`,field('amount','Monto del abono · MXN',Domain.outstanding(item)/100,'text','inputmode="decimal" required',true)+field('date','Fecha',Domain.today(),'date','required',true)+check('link',`Crear ${collection==='bills'?'gasto':'ingreso'} vinculado en Finanzas (una sola vez)`,true),d=>{const p={id:paymentId,amount:Domain.cents(d.amount),date:d.date,link:!!d.link,created_at:new Date().toISOString()};Store.save(s=>Domain.linkedPayment(s,collection,id,p));},'Confirmar abono');}
 function task(skillId,taskId){const skill=Store.list('skills').find(s=>s.id===skillId),t=skill.tasks.find(t=>t.id===taskId)||{};form(taskId?'Editar actividad':'Agregar una actividad','Asigna puntos según dificultad e importancia. La evidencia es obligatoria para la prueba final.',field('title','Actividad',t.title,'text','required',true)+select('level','Nivel',[[0,'Fundamentos'],[1,'Nivel básico'],[2,'Aplicación práctica'],[3,'Nivel intermedio'],[4,'Nivel avanzado'],[5,'Dominio'],[6,'Proyecto final']],t.level||0)+field('points','Puntos',t.points||2,'number','min="1" max="100" step="1" required')+area('evidence','Evidencia / resultado / referencia al cliente',t.evidence)+check('final','Es una prueba o proyecto final',t.final)+(taskId?check('remove','Eliminar esta actividad (el progreso se recalculará)',false):''),d=>{if(t.final&&t.done&&!d.evidence.trim()&&!d.remove)throw new Error('La prueba final completada necesita evidencia.');Store.save(s=>{const target=s.skills.find(x=>x.id===skillId);if(d.remove){target.tasks=target.tasks.filter(x=>x.id!==taskId);}else{const next={...t,id:taskId||Store.uuid(),title:d.title.trim(),points:Number(d.points),level:Number(d.level),final:!!d.final,evidence:d.evidence.trim(),done:t.done||false};if(!next.title)throw new Error('Escribe el nombre de la actividad.');if(taskId)target.tasks=target.tasks.map(x=>x.id===taskId?next:x);else target.tasks.push(next);}if(Domain.learningProgress(target)<100&&target.status==='Completada')target.status='Activa';});});}
 function study(id){form('Una sesión que suma','Registra el tiempo de práctica y lo que te llevas.',field('minutes','Minutos de estudio',25,'number','min="1" max="1440" step="1" required')+field('date','Fecha',Domain.today(),'date','required')+area('note','¿Qué practicaste o aprendiste?'),d=>Store.put('studySessions',{skillId:id,minutes:Number(d.minutes),date:d.date,note:d.note}));}
 function journal(r={},id){const draft=!id?localStorage.getItem(DALI_CONFIG.storageKey+'-journal-draft')||'':'';form(id?'Tu día, en tus palabras':'Un momento para ti','Escribe libremente o dicta. La estructura y las autoevaluaciones son manuales: no hay IA conectada.',field('title','Un título para este día',r.title||'','text','required',true)+field('date','Fecha',r.date||Domain.today(),'date','required',true)+area('text','Tu relato',r.text||draft,'required rows="6"')+area('summary','Resumen (tú decides qué destacar)',r.summary)+area('personal','Personal y relaciones',r.personal)+area('school','Escuela',r.school)+area('work','Trabajo y negocios',r.work)+area('soma','SOMA y ventas',r.soma)+area('gym','Gimnasio y salud',r.gym)+area('achievements','Logros',r.achievements)+area('difficulties','Dificultades y qué podrías mejorar',r.difficulties)+area('learning','Aprendizaje del día',r.learning)+area('nextAction','Pendientes / siguiente acción',r.nextAction)+field('productivity','Productividad autoevaluada (0–100)',r.productivity??50,'number','min="0" max="100" step="1" required')+field('mood','Cómo te sientes (opcional)',r.mood||'')+area('reason','¿Por qué elegiste esa productividad?',r.reason)+field('tags','Etiquetas, separadas por comas',(r.tags||[]).join(', '),'text','',true),d=>{const next={...d,title:d.title.trim(),text:d.text.trim(),summary:d.summary.trim(),productivity:Number(d.productivity),tags:d.tags.split(',').map(t=>t.trim()).filter(Boolean)};if(!Domain.validateJournal(next))throw new Error('Revisa el título, el relato y la productividad (de 0 a 100).');Store.put('journal',next,id);if(!id)localStorage.removeItem(DALI_CONFIG.storageKey+'-journal-draft');},'Confirmar y guardar');if(!id)document.getElementById('field-text').addEventListener('input',event=>{try{localStorage.setItem(DALI_CONFIG.storageKey+'-journal-draft',event.target.value);}catch{App.toast('No se pudo guardar el borrador. Exporta tus datos y revisa el almacenamiento.','error');}});}
 function profile(){const p=Store.get().profile;form('Tu perfil','Esta información se almacena en el navegador, sin autenticación ni cifrado.',field('name','Nombre completo',p.name,'text','required',true)+field('preferred','Nombre preferido',p.preferred,'text','required')+field('birth','Fecha de nacimiento',p.birth,'date',`required max="${Domain.today()}"`)+field('location','Ubicación',p.location,'text','',true)+field('role','Ocupación / rol',p.role,'text','',true)+field('school','Institución',p.school,'text','',true)+field('languages','Idiomas',p.languages,'text','',true)+area('interests','Intereses',p.interests)+field('projects','Proyectos activos',p.projects,'text','',true)+field('financialGoal','Meta neta mensual · MXN',p.financialGoal/100,'text','inputmode="decimal" required',true)+area('bio','Tu manifiesto',p.bio),d=>{if(!d.name.trim()||!d.preferred.trim())throw new Error('El nombre no puede estar vacío.');Store.save(s=>{s.profile={...d,name:d.name.trim(),preferred:d.preferred.trim(),financialGoal:Domain.cents(d.financialGoal)};});});}
 return {field,select,area,check,form,edit,payment,task,study,journal,profile,amountStep};
})();
