'use strict';
window.SpeechInput=(()=>{
  let active=null,observer=null;
  const supported=()=>window.SpeechRecognition||window.webkitSpeechRecognition;
  function stop(discard=true){if(!active)return;const session=active;active=null;try{session.recognition?.abort();}catch{}session.button.textContent='Dictar';if(discard)session.panel.remove();}
  function attach(root=document){let added=false;root.querySelectorAll('textarea:not([readonly]):not([data-no-dictate]),input[type="text"],input[type="search"],input:not([type])').forEach(field=>{
    if(field.dataset.dictationReady||field.disabled||field.readOnly||field.matches('[data-no-dictate],[inputmode="decimal"],[inputmode="numeric"],#money-pad-input')||field.closest('.speech-review'))return;
    added=true;field.dataset.dictationReady='true';if(!field.id)field.id='voice-'+crypto.randomUUID();const control=document.createElement('div');control.className='speech-control';const button=document.createElement('button');button.type='button';button.className='speech-trigger';button.innerHTML='<i data-lucide="mic"></i><span>Dictar</span>';const label=document.querySelector(`label[for="${CSS.escape(field.id)}"]`);button.setAttribute('aria-label','Dictar '+(label?.textContent||field.getAttribute('aria-label')||'texto'));button.title=supported()?'Dictar y revisar antes de insertar':'Dictado no compatible; puedes escribir manualmente';button.onclick=()=>start(field,button);control.append(button);
    if(field.parentElement.classList.contains('form-field'))field.after(control);else{const wrap=document.createElement('div');wrap.className='studio-speech-wrap';field.before(wrap);wrap.append(field,control);}
  });if(added&&window.lucide)lucide.createIcons();}
  function start(field,button){if(active?.field===field){stop();return;}stop();const Recognition=supported();if(!Recognition){App.toast('Este navegador no admite dictado. Puedes escribir el texto.','error');return;}if(!window.confirm('El reconocimiento puede enviar audio al proveedor de tu navegador. DALI OS no guarda audio. ¿Quieres dictar este campo?'))return;
    const panel=document.createElement('div');panel.className='speech-review';panel.innerHTML='<p role="status">Solicitando permiso del micrófono…</p><textarea data-no-dictate aria-label="Transcripción para revisar" placeholder="Tu transcripción aparecerá aquí…"></textarea><div class="speech-review-actions"><button type="button" class="stop">Detener</button><button type="button" class="apply">Añadir al campo</button><button type="button" class="cancel">Descartar</button></div>';button.parentElement.after(panel);const recognition=new Recognition(),session={field,button,panel,recognition};active=session;const output=panel.querySelector('textarea'),status=panel.querySelector('[role="status"]');button.textContent='Detener dictado';recognition.lang='es-MX';recognition.continuous=true;recognition.interimResults=true;
    recognition.onstart=()=>{if(active===session)status.textContent='Escuchando. Al terminar, revisa el texto y pulsa Añadir.';};
    recognition.onresult=event=>{if(active!==session)return;output.value=Array.from(event.results).map(r=>r[0].transcript).join(' ').trim();};
    recognition.onerror=event=>{if(active!==session)return;const errors={'not-allowed':'Permiso denegado. Habilita el micrófono o escribe manualmente.','audio-capture':'No se encontró un micrófono disponible.','network':'El servicio de dictado no está disponible. Puedes escribir manualmente.','no-speech':'No se detectó voz. Puedes revisar o descartar el texto.'};status.textContent=errors[event.error]||'El dictado se detuvo. Puedes escribir o revisar el texto.';};
    recognition.onend=()=>{if(active===session){panel.querySelector('.stop').disabled=true;if(status.textContent.startsWith('Escuchando'))status.textContent='Dictado detenido. Revisa el texto antes de añadirlo.';button.textContent='Cerrar dictado';}};
    panel.querySelector('.stop').onclick=()=>{try{recognition.stop();}catch{}};
    panel.querySelector('.cancel').onclick=()=>{stop();field.focus();};
    panel.querySelector('.apply').onclick=()=>{if(!field.isConnected){stop();return;}const text=output.value.trim();if(!text){status.textContent='No hay texto para añadir.';return;}const next=(field.value.trim()+(field.value.trim()?' ':'')+text);if(field.maxLength>0&&next.length>field.maxLength){status.textContent='El texto supera el límite del campo. Recorta la transcripción antes de añadirla.';return;}stop();field.value=next;field.dispatchEvent(new Event('input',{bubbles:true}));document.getElementById(field.id)?.focus();};
    try{recognition.start();}catch{status.textContent='No se pudo iniciar el dictado. Puedes escribir en la transcripción.';}
  }
  function init(){attach();observer=new MutationObserver(()=>{if(active&&!active.field.isConnected)stop();attach();});observer.observe(document.body,{childList:true,subtree:true});document.getElementById('app-dialog').addEventListener('close',()=>stop());window.addEventListener('hashchange',()=>stop());window.addEventListener('pagehide',()=>{stop();observer.disconnect();});}
  return {attach,init,start,stop,supported};
})();
