'use strict';
window.runStudioTests=async ({test,assert,equal,rejects,wait,until,w,doc,act,fill,submit,click})=>{
 const T=w.Tutor,plan=T.sample();plan.plan_id='qa-training';plan.title='Plan de prueba QA';plan.days[0].weekday=new Date(w.Domain.today()+'T12:00:00Z').getUTCDay();plan.days[0].exercises[0].name='Ejercicio QA';
 await test('Tutor: ruta y mapa accesible',async()=>{w.location.hash='gimnasio/tutor';await until(()=>doc.querySelector('.tutor-page'));assert(doc.querySelector('.anatomy-svg'));equal(doc.querySelectorAll('.muscle-picker button').length,10);});
 await test('Tutor: esquema, rangos y tamaño máximo',()=>{T.validatePlan(plan);rejects(()=>T.parse('{bad'));rejects(()=>T.parse(' '.repeat(262145)));rejects(()=>T.validatePlan({...plan,script:'alert(1)'}));const bad=structuredClone(plan);bad.days[0].exercises[0].reps_min=40;rejects(()=>T.validatePlan(bad));const dup=structuredClone(plan);dup.days.push(structuredClone(dup.days[0]));rejects(()=>T.validatePlan(dup));});
 await test('Tutor: validar y cancelar no modifica datos',async()=>{const before=JSON.stringify(w.Store.get());await act('tutor-import');doc.getElementById('tutor-json').value=JSON.stringify(plan);await click('#tutor-validate');assert(doc.querySelector('#tutor-apply'));equal(JSON.stringify(w.Store.get()),before);w.App.closeDialog();equal(JSON.stringify(w.Store.get()),before);});
 await test('Tutor: importar conserva historial y respaldo previo',async()=>{const sessions=JSON.stringify(w.Store.get().sessions),count=w.Store.list('routines').length;await act('tutor-import');doc.getElementById('tutor-json').value=JSON.stringify(plan);await click('#tutor-validate');await click('#tutor-apply');equal(w.Store.list('routines').length,count+1);equal(JSON.stringify(w.Store.get().sessions),sessions);assert(w.localStorage.getItem(w.DALI_CONFIG.storageKey+'-before-tutor'));equal(T.active().plan.plan_id,'qa-training');});
 await test('Tutor: reimportación idempotente con claves reordenadas',()=>{const n=w.Store.list('routines').length;equal(T.importDocument(plan),false);equal(T.importDocument(Object.fromEntries(Object.entries(plan).reverse())),false);equal(w.Store.list('routines').length,n);rejects(()=>T.importDocument({...plan,title:'Cambio sin subir versión'}));});
 await test('Tutor: nueva versión preserva sesiones',()=>{const snapshot=JSON.stringify(w.Store.get().sessions),p2=structuredClone(plan);p2.revision=2;p2.days[0].exercises[0].sets=2;T.importDocument(p2);equal(T.data().plans.length,2);equal(JSON.stringify(w.Store.get().sessions),snapshot);equal(T.active().plan.revision,2);});
 await test('Tutor: sesión hereda prescripción sin inventar resultados',async()=>{await act('start-workout',{id:T.active().routine_ids[0]});const s=w.Store.list('sessions').at(-1);equal(s.sets.length,2);equal(s.sets[0].repsMin,8);equal(s.sets[0].repsMax,12);equal(s.sets[0].muscle,'chest');assert(s.sets.every(x=>!x.done&&x.weight===0&&x.reps===0));equal(s.tutorKey,'qa-training@2');w.Store.put('sessions',{sets:s.sets.map((x,j)=>j===0?{...x,reps:10,weight:20,done:true}:x),finished:true},s.id);});
 await test('Tutor: mapa suma solo series completadas una vez',()=>{const m=T.statistics();equal(m.groups.chest,1);equal(m.sets,Object.values(m.groups).reduce((n,x)=>n+x,0));assert(m.groups.unclassified>=1);equal(m.volume,w.Store.list('sessions').filter(s=>s.finished).flatMap(s=>s.sets).filter(s=>s.done).reduce((n,s)=>n+s.weight*s.reps,0));});
 await test('Tutor: rango no premia duplicados del mismo día',()=>{equal(T.rank().done,1);equal(T.rank().name,'Bronce');const state=structuredClone(w.Store.get());state.sessions.push({...state.sessions.at(-1),id:w.crypto.randomUUID()});equal(T.rank(state).done,1);});
 await test('Tutor: revisión valida referencias y no cambia el plan',()=>{const r={schema_version:1,kind:'dali.training.review',review_id:'review-qa',plan_id:'qa-training',revision:2,summary:'Datos de prueba',observations:[{text:'Se registró una serie.',session_ids:[w.Store.list('sessions').at(-1).id]}],suggestions:['Registrar otra sesión antes de comparar.']},before=JSON.stringify(T.active()),bad=structuredClone(r);bad.observations[0].session_ids=['missing-session'];rejects(()=>T.importDocument(bad));T.importDocument(r);equal(T.data().reviews.length,1);equal(JSON.stringify(T.active()),before);equal(T.importDocument(r),false);});
 await test('Tutor: exportación excluye identidad y otros módulos',()=>{const data=T.exportContext();assert(!('profile'in data));assert(!('transactions'in data));assert(!('journal'in data));assert(!JSON.stringify(data).includes(w.Store.get().profile.name));assert(data.sessions.length>0);});
 await test('Tutor: respaldo conserva planes y rechaza prescripciones corruptas',()=>{const backup=structuredClone(w.Store.get()),n=T.data().plans.length;w.Store.merge(backup);equal(T.data().plans.length,n);const bad=structuredClone(backup);bad.routines.find(r=>r.tutorKey).prescription[0].sets=7;rejects(()=>w.Store.merge(bad));});
 await test('Tutor: controles frontal/posterior, grupos y versiones',async()=>{w.location.hash='gimnasio/tutor';await wait(60);await act('tutor-side',{side:'back'});assert(doc.querySelector('.anatomy-svg').getAttribute('aria-label').includes('posterior'));await act('tutor-muscle',{muscle:'back'});equal(doc.querySelector('.muscle-picker [aria-pressed="true"]').dataset.muscle,'back');await act('tutor-tab',{tab:'plans'});assert(doc.querySelectorAll('.saved-plan').length>=2);});
 await test('Finanzas: categorías SVG conservan el valor del formulario',async()=>{await act('add-transaction');doc.querySelector('#money-pad-input').value='19.99';await act('amount-next');assert(doc.querySelector('.category-picker .pixel-icon use'));await click('[data-category-value="Comida"]');equal(doc.querySelector('[name="category"]').value,'Comida');w.App.closeDialog();});
 await test('Dictado: revisión sin duplicados ni guardado automático (mock)',async()=>{const original=w.SpeechRecognition,webkit=w.webkitSpeechRecognition,confirm=w.confirm;let instance;class Fake{constructor(){instance=this;}start(){this.onstart?.();}stop(){this.onend?.();}abort(){this.onend?.();}}try{w.SpeechRecognition=Fake;w.webkitSpeechRecognition=undefined;w.confirm=()=>true;await act('add-goal');fill('title','Base');const field=doc.querySelector('[name="title"]'),button=field.parentElement.querySelector('.speech-trigger');assert(button);button.click();const event={results:[[{transcript:'texto dictado'}]]};instance.onresult(event);instance.onresult(event);equal(field.value,'Base');await click('.speech-review .apply');equal(field.value,'Base texto dictado');assert(doc.querySelector('#record-form'));assert(!doc.querySelector('.speech-review'));w.App.closeDialog();}finally{w.SpeechRecognition=original;w.webkitSpeechRecognition=webkit;w.confirm=confirm;w.SpeechInput.stop();}});
};
