'use strict';
(async () => {
  let passed=0, failed=0, skipped=0;
  const results=document.getElementById('test-results');
  const assert=(value,message='La condición no se cumple')=>{if(!value)throw new Error(message);};
  const equal=(actual,expected)=>assert(actual===expected,`Esperado ${expected}; recibido ${actual}`);
  const rejects=fn=>{let threw=false;try{fn();}catch{threw=true;}assert(threw,'Se esperaba un error de validación');};
  async function test(name,fn){const li=document.createElement('li');try{await fn();passed++;li.textContent='✓ '+name;li.className='green-text';console.log('PASS '+name);}catch(err){failed++;li.textContent='✕ '+name+' — '+err.message;li.className='red-text';console.error('FAIL '+name+': '+err.message);}results.append(li);}
  function skip(name){skipped++;const li=document.createElement('li');li.textContent='PENDIENTE · '+name;li.className='muted';results.append(li);console.log('SKIP '+name);}
  const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  async function until(fn,timeout=60000){const end=Date.now()+timeout;while(Date.now()<end){if(fn())return;await wait(80);}throw new Error('Tiempo de espera agotado');}
  const D=Domain;
  await test('Precisión monetaria: 0.10 + 0.20 = 30 centavos',()=>equal(D.cents('0.10')+D.cents('0.20'),30));
  await test('Importes inválidos, negativos y más de dos decimales rechazados',()=>{for(const value of ['-1','1.234','1e6','Infinity','', '10,50'])rejects(()=>D.cents(value));});
  await test('Formato de moneda MXN con dos decimales',()=>assert(D.money(123456).includes('1,234.56')));
  await test('Saldo = ingresos menos gastos, sin registros eliminados',()=>equal(D.balance([{type:'income',amount:10005},{type:'expense',amount:2300},{type:'income',amount:9999,deleted_at:'2026-09-01'}]),7705));
  await test('Préstamo con dos abonos parciales: saldo restante correcto',()=>equal(D.outstanding({amount:100000,payments:[{amount:25000},{amount:12500}]}),62500));
  await test('SOMA ↔ Finanzas: repetir un identificador no duplica el cobro',()=>{const s={clients:[{id:'client',title:'QA',amount:10000,payments:[]}],transactions:[]},p={id:'payment',amount:2500,date:'2026-09-13',link:true};equal(D.linkedPayment(s,'clients','client',p),true);equal(D.linkedPayment(s,'clients','client',p),false);equal(s.transactions.length,1);equal(D.outstanding(s.clients[0]),7500);});
  await test('Un abono mayor al saldo se rechaza sin mutaciones',()=>{const s={bills:[{id:'bill',title:'QA',amount:100,payments:[]}],transactions:[]};rejects(()=>D.linkedPayment(s,'bills','bill',{id:'p',amount:200,link:true}));equal(s.bills[0].payments.length,0);});
  await test('Progreso ponderado por puntos, no por casillas',()=>equal(D.learningProgress({tasks:[{points:1,done:true},{points:3,done:false}]}),25));
  await test('El 100% exige prueba final y evidencia',()=>{equal(D.learningProgress({tasks:[{points:5,done:true,final:true,evidence:''}]}),99);equal(D.learningProgress({tasks:[{points:5,done:true,final:true,evidence:'Cliente real documentado'}]}),100);});
  await test('Edad dinámica antes y después del cumpleaños',()=>{equal(D.age('2008-12-06','2026-12-05'),17);equal(D.age('2008-12-06','2026-12-06'),18);});
  await test('Medianoche calculada en America/Mexico_City',()=>{equal(D.today(new Date('2026-09-13T05:59:00Z')),'2026-09-12');equal(D.today(new Date('2026-09-13T06:00:00Z')),'2026-09-13');});
  await test('Objetivos: archivo histórico, renovación e idempotencia',()=>{const gs=[{recurring:true,horizon:'diario',periodKey:'2026-09-12',target:1,progress:1,history:[]}];equal(D.renewGoals(gs,'2026-09-13'),true);equal(gs[0].history[0].progress,1);equal(gs[0].progress,0);equal(D.renewGoals(gs,'2026-09-13'),false);equal(gs[0].history.length,1);});
  await test('Periodos semanales (lunes), mensuales y anuales',()=>{equal(D.periodKey('semanal','2026-09-13'),'2026-09-07');equal(D.periodKey('mensual','2026-09-13'),'2026-09');equal(D.periodKey('anual','2026-09-13'),'2026');});
  await test('Contrato de bitácora: JSON válido y rechazo de campos incorrectos',()=>{const j={title:'Mi día',text:'Estudié ventas.',summary:'Práctica',productivity:60,reason:'Estudié 30 minutos',tags:['ventas']};assert(D.validateJournal(j));assert(!D.validateJournal({...j,productivity:101}));assert(!D.validateJournal({...j,tags:'ventas'}));assert(!D.validateJournal({}));});
  await test('Entradas HTML se representan como texto, sin ejecución',()=>equal(D.escape('<img src=x onerror=alert(1)>'),'&lt;img src=x onerror=alert(1)&gt;'));
  skip('Protección de rutas, RLS y autenticación: no implementadas; requiere infraestructura compatible y autorización.');
  const frame=document.getElementById('test-app'),qaId=crypto.randomUUID(),key='dali-os-qa-'+qaId;
  frame.src='index.html?qa='+qaId+'#inicio';
  let w,doc;
  try {
    await until(()=>frame.contentWindow?.DALI_READY);
    w=frame.contentWindow;doc=w.document;
    const click=async selector=>{const node=doc.querySelector(selector);assert(node,'No se encontró '+selector);node.click();await wait(30);};
    const fill=(name,value)=>{const node=doc.querySelector(`[name="${name}"]`);assert(node,'Campo no encontrado: '+name);if(node.type==='checkbox')node.checked=value;else node.value=value;};
    const submit=async()=>{const form=doc.querySelector('#record-form');assert(form,'Formulario no encontrado');assert(form.checkValidity(),'Validación HTML fallida');form.requestSubmit();await wait(40);const error=doc.querySelector('#form-error');if(error?.textContent)throw new Error(error.textContent);assert(!doc.querySelector('#app-dialog').open,'El formulario no se cerró');};
    const act=async(action,extra={})=>{await w.App.action({dataset:{action,...extra}});await wait(35);};
    await test('Almacenamiento QA separado de los datos personales',()=>{equal(w.DALI_CONFIG.storageKey,key);equal(w.Store.list('transactions').length,0);});
    await test('Cancelar un formulario válido NO guarda el registro',async()=>{await act('add-goal');fill('title','No guardar');await click('#record-form [data-action="close-dialog"]');equal(w.Store.list('goals').length,0);assert(!doc.querySelector('#app-dialog').open);});
    await test('Movimiento: pad → detalles → guardar ingreso',async()=>{await act('add-transaction');await act('amount-type',{type:'income'});for(const digit of ['1','2','3','.','4','5'])await act('pad',{key:digit});await act('amount-next');fill('title','Ingreso de prueba');await submit();equal(w.Store.list('transactions').length,1);equal(w.Store.list('transactions')[0].amount,12345);equal(w.Store.list('transactions')[0].type,'income');});
    await test('Edición de movimiento conserva el UUID y precisión',async()=>{const t=w.Store.list('transactions')[0];await act('edit',{collection:'transactions',id:t.id});fill('amount','150.01');await submit();equal(w.Store.list('transactions')[0].id,t.id);equal(w.Store.list('transactions')[0].amount,15001);});
    await test('Objetivo recurrente: crear y completar desde la interfaz',async()=>{await act('add-goal');fill('title','Practicar ventas');fill('recurring',true);await submit();const g=w.Store.list('goals')[0];await act('toggle-goal',{id:g.id});equal(w.Store.list('goals')[0].progress,1);assert(w.Store.list('goals')[0].recurring);});
    await test('Pago pendiente: crear, abonar y vincular un gasto',async()=>{await act('add-bill');fill('title','Servicio de prueba');fill('amount','1000');await submit();const bill=w.Store.list('bills')[0];await act('payment',{collection:'bills',id:bill.id});fill('amount','250');await submit();equal(D.outstanding(w.Store.list('bills')[0]),75000);const t=w.Store.list('transactions').find(t=>t.source==='bills');equal(t.amount,25000);equal(t.type,'expense');});
    await test('Cliente SOMA: contrato, entregables y cobro vinculado',async()=>{const client=w.Store.list('clients')[0];await act('edit',{collection:'clients',id:client.id});fill('amount','2000');fill('deliverablesText','Sitio web\nCódigo QR');fill('phone','+52 341 123 4567');await submit();await act('payment',{collection:'clients',id:client.id});fill('amount','500');await submit();const saved=w.Store.list('clients')[0];equal(saved.deliverables.length,2);equal(saved.phone,'523411234567');equal(D.outstanding(saved),150000);equal(w.Store.list('transactions').filter(t=>t.source==='clients').length,1);});
    await test('Revertir cobro actualiza saldo y elimina movimiento activo',async()=>{const client=w.Store.list('clients')[0],payment=client.payments[0];await act('revert-payment',{collection:'clients',id:client.id,payment:payment.id});await click('#confirm-action');equal(D.outstanding(w.Store.list('clients')[0]),200000);equal(w.Store.list('transactions').filter(t=>t.source==='clients').length,0);});
    await test('Gimnasio: iniciar, guardar serie y completar sesión',async()=>{const r=w.Store.list('routines')[0];await act('start-workout',{id:r.id});await until(()=>doc.querySelector('[data-session]'));let s=w.Store.list('sessions')[0];const set=s.sets[0];for(const [field,value] of [['weight',40],['reps',10]]){const input=doc.querySelector(`[data-set="${set.id}"][data-field="${field}"]`);input.value=value;input.dispatchEvent(new w.Event('change',{bubbles:true}));}await act('complete-set',{id:s.id,set:set.id});await act('finish-workout',{id:s.id});await click('#confirm-action');s=w.Store.list('sessions')[0];assert(s.finished);equal(s.sets[0].weight*s.sets[0].reps,400);});
    await test('Aprendizaje: añadir actividad ponderada y registrar estudio',async()=>{const skill=w.Store.list('skills')[0];await act('add-task',{id:skill.id});fill('title','Practicar un pitch');fill('points',3);await submit();const t=w.Store.list('skills')[0].tasks.at(-1);await act('toggle-task',{id:skill.id,task:t.id});assert(w.Store.list('skills')[0].tasks.at(-1).done);await act('study',{id:skill.id});fill('minutes',35);await submit();equal(w.Store.list('studySessions')[0].minutes,35);});
    await test('Bitácora: borrador manual, validación y guardado confirmado',async()=>{await act('add-journal');fill('title','Un día de prueba');fill('text','Practiqué mi pitch y entrené.');fill('summary','Práctica y entrenamiento');fill('reason','Hice las actividades que había planeado.');fill('productivity',70);fill('tags','SOMA, gimnasio');await submit();const j=w.Store.list('journal')[0];equal(j.productivity,70);equal(j.tags.length,2);assert(D.validateJournal(j));});
    await test('Mi perfil: edición y edad calculada, no almacenada',async()=>{await act('edit-profile');fill('preferred','Dali QA');await submit();equal(w.Store.get().profile.preferred,'Dali QA');assert(!('age' in w.Store.get().profile));});
    await test('Eliminar y recuperar un objetivo desde la papelera',async()=>{const g=w.Store.list('goals')[0];await act('delete',{collection:'goals',id:g.id});await click('#confirm-action');equal(w.Store.list('goals').length,0);await act('restore',{collection:'goals',id:g.id});equal(w.Store.list('goals').length,1);w.App.closeDialog();});
    await test('Respaldo JSON: importación idempotente sin duplicados',()=>{const backup=JSON.parse(JSON.stringify(w.Store.get())),count=w.Store.get().transactions.length;w.Store.merge(backup);w.Store.merge(backup);equal(w.Store.get().transactions.length,count);});
    await test('Importación corrupta rechazada sin sobrescribir datos',()=>{const before=JSON.stringify(w.Store.get()),bad=JSON.parse(before);bad.transactions[0].amount=-1;rejects(()=>w.Store.merge(bad));equal(JSON.stringify(w.Store.get()),before);});
    await test('Búsqueda global encuentra datos reales',async()=>{await act('search');const input=doc.querySelector('#global-search');input.value='Ingreso de prueba';input.dispatchEvent(new w.Event('input'));assert(doc.querySelector('#search-results').textContent.includes('Ingreso de prueba'));w.App.closeDialog();});
    await test('Todas las rutas de módulos se renderizan sin error',async()=>{for(const [route] of w.DALI_CONFIG.sections){w.location.hash=route;await wait(50);assert(doc.querySelector('main h1'),'Falta encabezado en '+route);assert(!doc.querySelector('main').textContent.includes('undefined'),'Texto indefinido en '+route);}});
    await test('Renovación recupera periodos sin visitas, sin inventar cumplimiento',()=>{const goals=[{recurring:true,horizon:'diario',periodKey:'2026-09-10',target:1,progress:1,history:[]}];D.renewGoals(goals,'2026-09-13');equal(goals[0].history.length,3);equal(goals[0].history[1].recorded,false);equal(goals[0].history[1].progress,0);D.renewGoals(goals,'2026-09-13');equal(goals[0].history.length,3);});
    await test('Filtros por monto y fecha respetan todo el historial',async()=>{await act('finance-filters');fill('min','100');fill('max','200');await submit();equal(w.UI.period,'all');equal(w.Views.filteredTransactions().length,1);equal(w.Views.filteredTransactions()[0].amount,15001);await act('clear-finance-filters');equal(w.Views.filteredTransactions().length,2);});
    await test('Un concepto HTML no ejecuta código en los formularios',async()=>{const g=w.Store.list('goals')[0];w.Store.put('goals',{title:'<img src=x onerror=alert(1)>',target:2},g.id);await act('toggle-goal',{id:g.id});assert(!doc.querySelector('.dialog-subtitle img'));assert(doc.querySelector('.dialog-subtitle').textContent.includes('<img'));w.App.closeDialog();});
    await test('Bitácora: lectura completa y propuesta de objetivo con confirmación',async()=>{const j=w.Store.list('journal')[0];w.Store.put('journal',{nextAction:'Revisar mi propuesta comercial',personal:'Conversé con un amigo.'},j.id);w.location.hash='bitacora/'+j.id;await wait(50);assert(doc.querySelector('main').textContent.includes('Conversé con un amigo.'));const count=w.Store.list('goals').length;await act('journal-goal',{id:j.id});equal(w.Store.list('goals').length,count);await submit();equal(w.Store.list('goals').length,count+1);});
    await test('Fotografía: subir, recortar, comprimir y persistir como Blob',async()=>{await act('profile-photo');const canvas=doc.createElement('canvas');canvas.width=800;canvas.height=600;const context=canvas.getContext('2d');context.fillStyle='#2964ee';context.fillRect(0,0,800,600);context.fillStyle='#ffffff';context.fillRect(200,100,300,300);const source=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));const transfer=new w.DataTransfer();transfer.items.add(new w.File([source],'qa-photo.png',{type:'image/png'}));const input=doc.querySelector('#photo-file');input.files=transfer.files;input.dispatchEvent(new w.Event('change'));await until(()=>!doc.querySelector('#photo-save').disabled);doc.querySelector('#photo-zoom').value='1.3';doc.querySelector('#photo-zoom').dispatchEvent(new w.Event('input'));await click('#photo-save');await until(()=>!doc.querySelector('#app-dialog').open);const stored=await w.ProfilePhoto.read();assert(stored&&stored.size>0);assert(['image/webp','image/png'].includes(stored.type));await w.ProfilePhoto.hydrate();assert(doc.querySelector('[data-profile-photo] img').src.startsWith('blob:'));await w.ProfilePhoto.write(null);await w.ProfilePhoto.hydrate();});
    await runStudioTests({test,assert,equal,rejects,wait,until,w,doc,act,fill,submit,click});
    await test('Tema oscuro se guarda en las preferencias',async()=>{await act('theme');equal(w.Store.get().preferences.theme,'dark');equal(doc.documentElement.dataset.theme,'dark');});
    await test('Persistencia real después de recargar la aplicación',async()=>{const before=w.Store.list('transactions').length;await new Promise(resolve=>{frame.addEventListener('load',resolve,{once:true});w.location.reload();});await until(()=>frame.contentWindow.DALI_READY);w=frame.contentWindow;doc=w.document;equal(w.Store.list('transactions').length,before);equal(w.Store.get().profile.preferred,'Dali QA');equal(w.Store.get().preferences.theme,'dark');});
  } catch(err){await test('Carga de la aplicación de pruebas',()=>{throw err;});}
  const summary=`${passed} correctas · ${failed} fallidas · ${skipped} pendiente`;
  document.getElementById('test-summary').textContent=summary;
  document.body.dataset.testsComplete='true';document.body.dataset.testsFailed=failed;
  console.log('RESULT '+summary);
  // Each run uses a new namespace. Remove only the local records created by this run.
  frame.remove();for(const item of [key,key+'-last-section',key+'-rest-end',key+'-journal-draft',key+'-before-tutor'])localStorage.removeItem(item);indexedDB.deleteDatabase(key+'-media');
})();
