'use strict';
window.TutorUI = (()=>{
  const e=Domain.escape,i=Views.icon,b=Views.button;
  function textDialog(title,text,filename){App.openDialog(title,`<p class="dialog-subtitle">Revisa el contenido antes de copiarlo. No se envía automáticamente a ningún servicio.</p><textarea class="code-output" id="tutor-output" readonly rows="14" aria-label="Contenido para copiar" data-no-dictate>${e(text)}</textarea><div class="form-footer">${b('Copiar','tutor-copy')}${b('Descargar','tutor-download','primary')}</div>`);document.querySelector('[data-action="tutor-download"]').onclick=()=>App.download(filename,text,filename.endsWith('.json')?'application/json':'text/plain;charset=utf-8');}
  function prompt(){Forms.form('Prepara las instrucciones','Solo se compartirán los campos que escribas aquí. No se incluye tu perfil, finanzas, fotos o bitácora.',Forms.area('goal','¿Qué quieres trabajar?','','required placeholder="Ej. volver a entrenar con constancia y registrar mis sesiones"')+Forms.field('availability','Días y tiempo disponible','','text','required placeholder="Ej. lunes, miércoles y viernes; 45 minutos"',true)+Forms.field('equipment','Equipo disponible','','text','required placeholder="Ej. mancuernas y banco"',true)+Forms.area('preferences','Experiencia, preferencias y límites que quieras compartir'),d=>{textDialog('Instrucciones para tu IA',Tutor.requestPrompt(d),'dali-instrucciones-tutor.txt');},'Preparar texto');}
  function importer(initial=''){App.openDialog('Importar plan o revisión',`<p class="dialog-subtitle">Pega el JSON de tu IA o abre un archivo. Primero validaremos; después podrás revisar y confirmar. Máximo 256 KB.</p><div class="import-actions"><label for="tutor-file" class="button">${i('folder-open')}Abrir archivo</label><input id="tutor-file" type="file" accept=".json,application/json" hidden>${b('Ver plantilla','tutor-template','small')}</div><label class="micro-label" for="tutor-json">JSON / PLAN O REVISIÓN</label><textarea id="tutor-json" class="code-output" data-no-dictate rows="12" spellcheck="false" placeholder="Pega aquí el objeto JSON…">${e(initial)}</textarea><p id="tutor-import-error" class="form-error" role="alert"></p><div class="form-footer">${b('Cancelar','close-dialog')}<button type="button" class="button primary" id="tutor-validate">${i('scan-text')}Validar y revisar</button></div>`);document.getElementById('tutor-file').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;try{if(file.size>256*1024)throw new Error('El archivo supera 256 KB.');document.getElementById('tutor-json').value=await file.text();document.getElementById('tutor-import-error').textContent='';}catch(err){document.getElementById('tutor-import-error').textContent=err.message;}};document.getElementById('tutor-validate').onclick=()=>{try{const raw=document.getElementById('tutor-json').value,p=Tutor.parse(raw);if(p.kind==='dali.training.review')Tutor.checkReview(p);preview(p,raw);}catch(err){document.getElementById('tutor-import-error').textContent=err.message;}};}
  function planBody(p){return `<div class="plan-preview"><h3>${e(p.title)}</h3><p>${e(p.goal)}</p>${p.notes?`<p class="notice">${e(p.notes)}</p>`:''}${p.days.map(d=>`<details open><summary>${TutorView.dayNames[d.weekday]} · ${e(d.title)}</summary>${d.exercises.map(x=>`<div class="preview-exercise"><strong>${e(x.name)}</strong><span>${e(Tutor.muscles[x.muscle])} · ${x.sets} × ${x.reps_min}–${x.reps_max} reps</span><small>RIR ${x.rir} · Descanso ${x.rest_seconds} s</small></div>`).join('')}</details>`).join('')}</div>`;}
  function preview(p,raw){const review=p.kind==='dali.training.review',existing=review?Tutor.data().reviews.find(x=>x.review_id===p.review_id):Tutor.data().plans.find(x=>Tutor.key(x.plan)===Tutor.key(p));const old=!review?Tutor.data().plans.filter(x=>x.plan.plan_id===p.plan_id).at(-1):null;App.openDialog(review?'Revisa la respuesta externa':'Revisa el plan antes de guardarlo',`<div class="notice">${i('shield-check')}Formato validado. Esto no certifica que el contenido sea adecuado para tu salud u objetivos.</div>${review?`<div class="plan-preview"><h3>${e(p.summary)}</h3>${p.observations.map(o=>`<p>${e(o.text)}<small>${o.session_ids.length} sesiones citadas</small></p>`).join('')}<ul>${p.suggestions.map(x=>`<li>${e(x)}</li>`).join('')}</ul></div>`:planBody(p)}<div class="import-diff"><strong>${existing?'Esta versión ya está guardada.':review?'Se añadirá una revisión, sin cambiar el plan.':old?'Nueva versión: v'+old.plan.revision+' → v'+p.revision:'Se añadirá un plan nuevo.'}</strong><p>${review?'Las sugerencias no se aplican automáticamente.':p.days.length+' rutinas nuevas. Tus rutinas y sesiones anteriores no se modificarán.'}</p></div><p class="tutor-small">Antes de continuar puedes descargar un respaldo completo. La primera aplicación de Tutor también conserva una copia local previa.</p>${b(i('download')+'Descargar respaldo','export-backup','small')}<p id="tutor-apply-error" class="form-error" role="alert"></p><div class="form-footer"><button type="button" class="button" id="tutor-back">Volver al JSON</button><button type="button" class="button primary" id="tutor-apply">${review?'Guardar revisión':'Confirmar plan'}</button></div>`);document.getElementById('tutor-back').onclick=()=>importer(raw);document.getElementById('tutor-apply').onclick=event=>{event.currentTarget.disabled=true;try{if(!Store.get().training&&!localStorage.getItem(DALI_CONFIG.storageKey+'-before-tutor'))localStorage.setItem(DALI_CONFIG.storageKey+'-before-tutor',JSON.stringify(Store.get()));const changed=Tutor.importDocument(p);App.closeDialog();TutorView.state.tab=review?'reviews':'overview';if(location.hash!=='#gimnasio/tutor')location.hash='gimnasio/tutor';else App.render();App.toast(changed?'Guardado. El historial anterior sigue intacto.':'Ya estaba guardado. No se ha duplicado nada.');}catch(err){event.currentTarget.disabled=false;document.getElementById('tutor-apply-error').textContent=err.message;}};}
  function exportReview(){const data=Tutor.exportContext();if(!data.sessions.length){App.openDialog('Todavía no hay sesiones para revisar',`<p class="dialog-subtitle">Registra y termina una sesión. Después podrás exportar sus series, cargas y repeticiones, sin incluir información de otros módulos.</p>${b('Cerrar','close-dialog','primary')}`);return;}textDialog('Revisa los datos que vas a compartir',JSON.stringify(data,null,2),'dali-progreso-'+Domain.today()+'.json');}
  function classify(){const names=[...new Set(Store.list('sessions').flatMap(s=>s.sets.filter(t=>!Object.hasOwn(Tutor.muscles,t.muscle)).map(t=>t.exercise)))];if(!names.length){App.openDialog('No hay ejercicios por clasificar','<p class="dialog-subtitle">Los ejercicios de planes importados ya incluyen un grupo principal. Tus próximos registros aparecerán aquí.</p>'+b('Cerrar','close-dialog','primary'));return;}Forms.form('Clasifica tus ejercicios anteriores','Elige un músculo principal por nombre de ejercicio. No se cambiarán series, cargas o fechas. La clasificación se usará para el desglose.',names.map((name,j)=>Forms.select('muscle_'+j,e(name),Object.entries(Tutor.muscles),Object.hasOwn(Tutor.data().labels,name)?Tutor.data().labels[name]:'unclassified',true)).join(''),d=>Store.save(s=>{s.training=s.training||{version:1,plans:[],reviews:[],active:null,labels:{}};names.forEach((name,j)=>Object.defineProperty(s.training.labels,name,{value:d['muscle_'+j],writable:true,enumerable:true,configurable:true}));}));}
  async function action(el){const a=el.dataset.action,id=el.dataset.id;
    if(a==='tutor-tab'){TutorView.state.tab=el.dataset.tab;App.render();return;}
    if(a==='tutor-side'){TutorView.state.side=el.dataset.side;App.render();return;}
    if(a==='tutor-muscle'){if(!Object.hasOwn(Tutor.muscles,el.dataset.muscle))return;TutorView.state.muscle=el.dataset.muscle;App.render();document.querySelector('.muscle-picker [aria-pressed="true"]')?.focus({preventScroll:true});return;}
    if(a==='tutor-prompt'){prompt();return;}if(a==='tutor-import'){importer();return;}
    if(a==='tutor-template'){textDialog('Plantilla de formato · no es una recomendación',JSON.stringify(Tutor.sample(),null,2),'dali-plan-plantilla.json');return;}
    if(a==='tutor-export'){exportReview();return;}
    if(a==='tutor-copy'){const text=document.getElementById('tutor-output').value;try{await navigator.clipboard.writeText(text);App.toast('Copiado. Pégalo en la IA que uses.');}catch{document.getElementById('tutor-output').select();App.toast('No se pudo copiar automáticamente. Selecciona y copia el texto.','error');}return;}
    if(a==='tutor-activate'){App.confirmAction('¿Usar esta versión del plan?','Los próximos entrenamientos usarán esta versión. El historial no cambia. El rango se calcula solo con los días registrados para la versión activa.',()=>{Store.save(s=>{if(!s.training?.plans.some(x=>Tutor.key(x.plan)===id))throw new Error('No se encontró el plan.');s.training.active=id;});App.toast('Plan activo actualizado.');},'Activar');return;}
    if(a==='tutor-plan-detail'){const item=Tutor.data().plans.find(x=>Tutor.key(x.plan)===id);if(!item)throw new Error('Plan no encontrado.');App.openDialog('Plan guardado · v'+item.plan.revision,planBody(item.plan)+`<div class="form-footer"><button type="button" class="button primary" id="plan-export">Descargar JSON</button>${b('Cerrar','close-dialog')}</div>`);document.getElementById('plan-export').onclick=()=>App.download('dali-plan-v'+item.plan.revision+'.json',JSON.stringify(item.plan,null,2),'application/json');return;}
    if(a==='tutor-classify'){classify();return;}
    if(a==='tutor-rank-info'){App.openDialog('Cómo se calcula tu rango',`<p class="dialog-subtitle">Se revisa la versión activa del plan, desde su importación y como máximo los últimos 28 días. Solo cuentan días programados hasta hoy con una sesión terminada de la rutina correspondiente y al menos una serie completada.</p><div class="rank-rules"><p><strong>Bronce</strong> · Al menos 1 día completado.</p><p><strong>Plata</strong> · Al menos 3 días y 60% de cumplimiento.</p><p><strong>Oro</strong> · Al menos 6 días y 80% de cumplimiento.</p></div><p class="dialog-subtitle">Varias sesiones en el mismo día cuentan una vez. Descansar no suma ni resta. Los días extra, el peso corporal y la carga levantada no dan puntos. Es un indicador de registro, no de capacidad física ni de calidad de entrenamiento.</p>${b('Entendido','close-dialog','primary')}`);return;}
  }
  return {action,importer,preview,prompt};
})();
