'use strict';
// Pure contracts and metrics. No AI endpoint, executable JSON or secret credentials.
window.Tutor = (() => {
  const muscles={chest:'Pecho',back:'Espalda',shoulders:'Hombros',biceps:'Bíceps',triceps:'Tríceps',core:'Abdomen',quads:'Cuádriceps',hamstrings:'Isquiotibiales',glutes:'Glúteos',calves:'Pantorrillas',unclassified:'Sin clasificar'};
  const key=p=>p.plan_id+'@'+p.revision;
  const canonical=value=>JSON.stringify(value,(k,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(key=>[key,v[key]])):v);
  const labelFor=(labels,name)=>Object.hasOwn(labels,name)?labels[name]:'unclassified';
  const fail=(path,message)=>{throw new Error(path+': '+message);};
  function obj(value,fields,path){if(!value||typeof value!=='object'||Array.isArray(value))fail(path,'se esperaba un objeto.');for(const field of Object.keys(value))if(!fields.includes(field))fail(path+'.'+field,'campo no permitido.');}
  function text(value,path,max=200){if(typeof value!=='string'||!value.trim()||value.length>max)fail(path,'usa texto de 1 a '+max+' caracteres.');}
  function slug(value,path){if(typeof value!=='string'||!/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,47}$/.test(value))fail(path,'usa un identificador de hasta 48 letras, números, guiones o guiones bajos.');}
  function integer(value,min,max,path){if(!Number.isInteger(value)||value<min||value>max)fail(path,'usa un entero entre '+min+' y '+max+'.');}
  function array(value,min,max,path){if(!Array.isArray(value)||value.length<min||value.length>max)fail(path,'se requieren entre '+min+' y '+max+' elementos.');}
  function validatePlan(p){
    obj(p,['schema_version','kind','plan_id','revision','title','goal','notes','days'],'plan');
    if(p.schema_version!==1||p.kind!=='dali.training.plan')fail('plan','formato o versión no compatible.');
    slug(p.plan_id,'plan_id');integer(p.revision,1,999,'revision');text(p.title,'title',100);text(p.goal,'goal',2000);
    if(p.notes!==undefined&&typeof p.notes!=='string')fail('notes','debe ser texto.');if((p.notes||'').length>4000)fail('notes','máximo 4000 caracteres.');
    array(p.days,1,7,'days');const ids=new Set(),weekdays=new Set(),catalog=new Map();
    p.days.forEach((day,n)=>{const path='days['+n+']';obj(day,['day_id','weekday','title','exercises'],path);slug(day.day_id,path+'.day_id');integer(day.weekday,0,6,path+'.weekday');text(day.title,path+'.title',100);
      if(ids.has(day.day_id)||weekdays.has(day.weekday))fail(path,'día o identificador duplicado.');ids.add(day.day_id);weekdays.add(day.weekday);array(day.exercises,1,16,path+'.exercises');const used=new Set();
      day.exercises.forEach((ex,j)=>{const at=path+'.exercises['+j+']';obj(ex,['exercise_id','name','muscle','sets','reps_min','reps_max','rir','rest_seconds'],at);slug(ex.exercise_id,at+'.exercise_id');text(ex.name,at+'.name',100);if(!Object.hasOwn(muscles,ex.muscle)||ex.muscle==='unclassified')fail(at+'.muscle','grupo muscular no válido.');integer(ex.sets,1,8,at+'.sets');integer(ex.reps_min,1,50,at+'.reps_min');integer(ex.reps_max,1,50,at+'.reps_max');if(ex.reps_min>ex.reps_max)fail(at,'el mínimo de repeticiones supera el máximo.');integer(ex.rir,0,5,at+'.rir');integer(ex.rest_seconds,30,600,at+'.rest_seconds');if(used.has(ex.exercise_id))fail(at,'ejercicio duplicado en el mismo día.');used.add(ex.exercise_id);const identity=ex.name+'|'+ex.muscle;if(catalog.has(ex.exercise_id)&&catalog.get(ex.exercise_id)!==identity)fail(at,'el mismo ejercicio tiene nombres o músculos distintos.');catalog.set(ex.exercise_id,identity);
      });
    });return p;
  }
  function validateReview(r){obj(r,['schema_version','kind','review_id','plan_id','revision','summary','observations','suggestions'],'review');if(r.schema_version!==1||r.kind!=='dali.training.review')fail('review','formato no compatible.');slug(r.review_id,'review_id');slug(r.plan_id,'plan_id');integer(r.revision,1,999,'revision');text(r.summary,'summary',4000);array(r.observations,0,20,'observations');array(r.suggestions,0,20,'suggestions');r.observations.forEach((o,n)=>{obj(o,['text','session_ids'],'observations['+n+']');text(o.text,'observation.text',1500);array(o.session_ids,1,30,'session_ids');o.session_ids.forEach(id=>{if(typeof id!=='string'||!/^[a-zA-Z0-9-]{1,80}$/.test(id))fail('session_ids','identificador inválido.');});});r.suggestions.forEach(x=>text(x,'suggestions',1500));return r;}
  function parse(raw){if(typeof raw!=='string'||new Blob([raw]).size>256*1024)fail('archivo','máximo 256 KB.');let p;try{p=JSON.parse(raw);}catch{fail('JSON','no se pudo leer. Pega solo el objeto JSON, sin bloques de código.');}if(p?.kind==='dali.training.review')return validateReview(p);return validatePlan(p);}
  const empty=()=>({version:1,plans:[],reviews:[],active:null,labels:{}});
  const data=(s=Store.get())=>s.training||empty();
  function validateExtension(t){if(!t)return true;if(t.version!==1||!Array.isArray(t.plans)||!Array.isArray(t.reviews)||t.plans.length>100||t.reviews.length>200||!t.labels||Array.isArray(t.labels)||typeof t.labels!=='object')fail('training','estructura local no válida.');const keys=new Set();for(const item of t.plans){validatePlan(item.plan);if(keys.has(key(item.plan)))fail('training','versión de plan duplicada.');keys.add(key(item.plan));if(typeof item.imported_at!=='string'||Number.isNaN(Date.parse(item.imported_at)))fail('training','fecha inválida.');if(!Array.isArray(item.routine_ids)||item.routine_ids.length!==item.plan.days.length||item.routine_ids.some(id=>typeof id!=='string'||!/^[a-zA-Z0-9-]{1,80}$/.test(id)))fail('training','referencias de rutinas no válidas.');}if(t.active!==null&&!keys.has(t.active))fail('training.active','plan inexistente.');const ids=new Set();for(const r of t.reviews){validateReview(r);if(ids.has(r.review_id))fail('training.reviews','revisión duplicada.');ids.add(r.review_id);}for(const [name,muscle]of Object.entries(t.labels))if(name.length>200||!Object.hasOwn(muscles,muscle))fail('training.labels','clasificación no válida.');return true;}
  const active=(s=Store.get())=>data(s).plans.find(x=>key(x.plan)===data(s).active)||null;
  function checkReview(r,s=Store.get()){if(!data(s).plans.some(x=>key(x.plan)===r.plan_id+'@'+r.revision))fail('review','primero importa el plan al que hace referencia.');const sessions=new Set(s.sessions.filter(x=>!x.deleted_at&&x.finished&&x.tutorKey===r.plan_id+'@'+r.revision).map(x=>x.id));for(const o of r.observations)for(const id of o.session_ids)if(!sessions.has(id))fail('review.session_ids','la sesión '+id+' no pertenece a esa versión del plan.');}
  function importDocument(p){p=structuredClone(p);if(p.kind==='dali.training.review'){validateReview(p);checkReview(p);const old=data().reviews.find(x=>x.review_id===p.review_id);if(old){if(canonical(old)!==canonical(p))fail('review_id','ya existe con otro contenido.');return false;}Store.save(s=>{s.training=s.training||empty();s.training.reviews.push(p);});return true;}
    validatePlan(p);const existing=data().plans.find(x=>key(x.plan)===key(p));if(existing){if(canonical(existing.plan)!==canonical(p))fail('revision','esa versión ya existe con otro contenido. Aumenta revision.');return false;}
    Store.save(s=>{s.training=s.training||empty();const routineIds=[];p.days.forEach(day=>{const r=Store.record({title:day.title,day:day.weekday,exercises:day.exercises.map(x=>x.name).join('\n'),prescription:structuredClone(day.exercises),tutorKey:key(p),tutorPlanId:p.plan_id});routineIds.push(r.id);s.routines.push(r);});s.training.plans.push({plan:p,routine_ids:routineIds,imported_at:new Date().toISOString()});s.training.active=key(p);});return true;
  }
  function mergeExtension(s,incoming){if(!incoming.training)return;validateExtension(incoming.training);s.training=s.training||empty();for(const item of incoming.training.plans){const old=s.training.plans.find(x=>key(x.plan)===key(item.plan));if(old&&canonical(old)!==canonical(item))fail('respaldo','dos copias distintas de la misma versión de plan. No se ha importado nada.');if(!old)s.training.plans.push(structuredClone(item));}for(const r of incoming.training.reviews){const old=s.training.reviews.find(x=>x.review_id===r.review_id);if(old&&canonical(old)!==canonical(r))fail('respaldo','revisión en conflicto.');if(!old)s.training.reviews.push(structuredClone(r));}for(const [name,muscle]of Object.entries(incoming.training.labels))if(!Object.hasOwn(s.training.labels,name))Object.defineProperty(s.training.labels,name,{value:muscle,enumerable:true,writable:true,configurable:true});if(!s.training.active)s.training.active=incoming.training.active;}
  function makeSets(r,previous,copy){if(!r.prescription)return null;return r.prescription.flatMap(ex=>Array.from({length:ex.sets},(_,index)=>{const prev=copy?previous?.sets.filter(s=>s.exerciseId===ex.exercise_id)[index]:null;return {id:Store.uuid(),exercise:ex.name,exerciseId:ex.exercise_id,muscle:ex.muscle,weight:prev?.weight||0,reps:prev?.reps||0,rir:ex.rir,repsMin:ex.reps_min,repsMax:ex.reps_max,restSeconds:ex.rest_seconds,done:false};}));}
  function statistics(s=Store.get(),days=28,today=Domain.today()){
    const date=new Date(today+'T12:00:00Z');date.setUTCDate(date.getUTCDate()-days+1);const from=date.toISOString().slice(0,10),sessions=s.sessions.filter(x=>!x.deleted_at&&x.finished&&x.date>=from&&x.date<=today),groups=Object.fromEntries(Object.keys(muscles).map(k=>[k,0]));let volume=0,sets=0;const exercises=new Map();
    for(const session of sessions)for(const set of session.sets.filter(x=>x.done)){const group=Object.hasOwn(muscles,set.muscle)?set.muscle:labelFor(data(s).labels,set.exercise);groups[group]++;sets++;volume+=set.weight*set.reps;const id=set.exerciseId?(session.tutorPlanId||'')+':'+set.exerciseId:'legacy:'+set.exercise;const item=exercises.get(id)||{id,name:set.exercise,muscle:group,sessions:new Map()};const entry=item.sessions.get(session.id)||{date:session.date,volume:0,sets:0,max:0};entry.volume+=set.weight*set.reps;entry.sets++;entry.max=Math.max(entry.max,set.weight);item.sessions.set(session.id,entry);exercises.set(id,item);}
    return {from,to:today,sessions,groups,sets,volume,exercises:[...exercises.values()].map(x=>({...x,history:[...x.sessions.values()].sort((a,b)=>a.date.localeCompare(b.date))}))};
  }
  function rank(s=Store.get(),today=Domain.today()){
    const plan=active(s);if(!plan)return {name:'Sin rango',level:0,percent:0,done:0,expected:0,from:today};const since=new Date(today+'T12:00:00Z');since.setUTCDate(since.getUTCDate()-27);const from=[since.toISOString().slice(0,10),Domain.today(new Date(plan.imported_at))].sort().at(-1);let expected=0,done=0;const until=new Date(today+'T12:00:00Z');for(let d=new Date(from+'T12:00:00Z');d<=until;d.setUTCDate(d.getUTCDate()+1)){const date=d.toISOString().slice(0,10),di=plan.plan.days.findIndex(x=>x.weekday===d.getUTCDay());if(di<0)continue;expected++;if(s.sessions.some(x=>!x.deleted_at&&x.finished&&x.tutorKey===key(plan.plan)&&x.routineId===plan.routine_ids[di]&&x.date===date&&x.sets.some(t=>t.done)))done++;}const percent=expected?Math.round(done/expected*100):0,level=done>=6&&percent>=80?3:done>=3&&percent>=60?2:done>=1?1:0;return {name:['Sin rango','Bronce','Plata','Oro'][level],level,percent,done,expected,from};
  }
  function sample(){return {schema_version:1,kind:'dali.training.plan',plan_id:'mi-plan',revision:1,title:'Mi plan de entrenamiento',goal:'Escribe aquí tu objetivo y revisa el plan antes de aplicarlo.',notes:'Plantilla de formato. No es una recomendación personalizada.',days:[{day_id:'dia-1',weekday:1,title:'Sesión A',exercises:[{exercise_id:'ejercicio-1',name:'Ejercicio a revisar',muscle:'chest',sets:3,reps_min:8,reps_max:12,rir:2,rest_seconds:90}]}]};}
  function requestPrompt(values){const context={kind:'dali.training.request',schema_version:1,goal:values.goal,availability:values.availability,equipment:values.equipment,preferences:values.preferences};return 'Ayúdame a preparar un borrador de entrenamiento que revisaré antes de usar. No inventes mi experiencia, mis cargas, lesiones, sesiones previas ni resultados. Si falta información importante, pregúntame antes de crear el plan. No diagnostiques ni prescribas tratamientos. No propongas entrenar con dolor.\n\nCONTEXTO QUE HE DECIDIDO COMPARTIR:\n'+JSON.stringify(context,null,2)+'\n\nCuando tengamos suficiente contexto, devuelve SOLO JSON, sin markdown, con esta estructura (los valores de la plantilla son ilustrativos, no instrucciones de entrenamiento):\n'+JSON.stringify(sample(),null,2)+'\nReglas: kind y schema_version fijos; plan_id y exercise_id estables de 1–48 letras/números/guiones; revision entero 1–999, incrementa al editar. days: 1–7, weekday 0=domingo a 6=sábado, sin días repetidos. Cada día 1–16 ejercicios; sets 1–8; reps_min y reps_max 1–50 con min<=max; rir 0–5; rest_seconds 30–600. Grupos válidos: '+Object.keys(muscles).filter(k=>k!=='unclassified').join(', ')+'. Un solo músculo principal por ejercicio. No añadas campos, cargas automáticas, HTML, scripts, enlaces ni puntuaciones de rango. Estos límites son de formato, no recomendaciones de dosis. Para una revisión posterior usa kind dali.training.review, schema_version 1, review_id, plan_id, revision, summary, observations [{text,session_ids}], suggestions [texto]. Cita únicamente IDs de sesiones que te haya compartido. No inventes evidencia ni afirmes causalidad.';}
  function exportContext(){const a=active(),m=statistics();return {kind:'dali.training.progress',schema_version:1,period:{from:m.from,to:m.to},plan:a?.plan||null,sessions:m.sessions.map(s=>({id:s.id,date:s.date,plan_key:s.tutorKey||null,title:s.title,sets:s.sets.filter(t=>t.done).map(t=>({exercise:t.exercise,exercise_id:t.exerciseId||null,muscle:t.muscle||labelFor(data().labels,t.exercise),weight_kg:t.weight,reps:t.reps,rir:t.rir}))})),computed:{volume_kg:m.volume,completed_sets:m.sets,groups:m.groups},note:'Solo registros de entrenamiento. No incluye identidad, finanzas, bitácora ni fotos. Los comentarios IA deben identificarse como propuestas.'};}
  return {muscles,key,canonical,parse,validatePlan,validateReview,validateExtension,mergeExtension,data,active,importDocument,makeSets,statistics,rank,sample,requestPrompt,exportContext,checkReview};
})();
